### ISSUE TITLE
bug in teacher granting authorization to student

### ISSUE THREAD

**Issue by yyynyc** [yyynyc/shooloo_v2#20]
Currently there is call_back for authorization. When an authorization is granted, an email will be sent to the grantee. However, students are not required to have personal email addresses, so when a teacher tries to grant an authorization to a student that does not have personal email address on file, the grant does not go through. We need to change the call_back to conditional call_back: if grantee has an email address, send the email; if not, then the call_back should not be executed and the granting of authorization should still go through.

**Comment by brentonmorris** [comment]
I think this is still important

**Comment by yyynyc** [comment]
ok. I've fixed the bug, instead of saying "if authorized.personal_email.nil?", I've changed it "if authorized.personal_email.blank?", and the call_back is no longer executed if the student does not have a personal email address.
