### ISSUE TITLE
Comparison view of the posts does not show up on laptops correctly

### ISSUE THREAD

**Issue by yyynyc** [yyynyc/shooloo_v2#23]
Currently comparison view of two posts (in lessons/show.html.erb) works well on desktops, but does not work on laptop. It shows two column view on the desktop, but shows only one column on laptop.

**Comment by yyynyc** [comment]
I've just tried it on my laptop in the local environment. The comparison view works in the local environment but does not work in production. In the past, whenever things like this happened, it was always caused by the javascript of the page being incompatible with the SSL environment. Right now, if you go to inspect page and then click on "Console", you will see an error message. 

We need to fix this issue ASAP as teachers are going to use this feature to teach their classes soon.

**Comment by yyynyc** [comment]
Ok. I've narrowed the error being related to CKEditor. event.returnDefault in the CKEditor-related javascript files need to be changed according to the error message.

**Comment by yyynyc** [comment]
Here are the stackoverflow discussion about the issue
http://stackoverflow.com/questions/20045162/event-returnvalue-is-deprecated-please-use-the-standard-event-preventdefault

**Comment by brentonmorris** [comment]
I upgraded the jquery-rails gem to get rid of the deprecation message, but I don't think that fixed anything. I sent you a screenshot of what it looks like on my machine.

**Comment by yyynyc** [comment]
You've fixed it. Thanks!

**Comment by yyynyc** [comment]
I've just checked my laptop in the production environment. The view is still one column instead of two. I will deploy your commits on Monday. Right now kids are using it, so I don't want the deployment to disrupt their usage.
